### ISSUE TITLE
Question about Config struct (migrating from 0.3.2 to 0.4.1)

### ISSUE THREAD

**Issue by Armiixteryx** [AlecTroemel/quickxml_to_serde#15]
Hello, thank you very much for this crate.

I was checking last version of this crate and trying to migrate some own projects which are currently using `0.3.2` version of this crate.

I am using `xml_string_to_json` fn to transform XML into JSON, which signature is following:

`pub fn xml_string_to_json(xml: String) -> Value`

Meanwhile in `0.4.1` version, signature has changed, including now a `Config` struct:

`pub fn xml_string_to_json(xml: String, config: &Config) -> Result<Value, Error>`

My question is following: `Default` impl for Config generates same JSON output as version `0.3.2` (which did not included `Config` struct)

Thanks for your help :)

**Comment by rimutaka** [comment]
@Armiixteryx , yes, the default should be the same as in v.0.3.2. Take a look at https://github.com/AlecTroemel/quickxml_to_serde/blob/master/src/lib.rs#L149 where the defaults are set just to double check that matches your expectations.

**Comment by AlecTroemel** [comment]
closing this, as question seems to be answered
