### ISSUE TITLE
Forcing a data type on a JSON property

### ISSUE THREAD

**Issue by rimutaka** [AlecTroemel/quickxml_to_serde#6]
I ran into a situation where the JSON is inconsistent which makes it difficult to deserialize the data back into a struct.

**Example 1**: an array with a single element looses `[ ]` and becomes a value/object.
* `{ "a": [1,2,3] }` - correct
* `{ "a": [1] }` - correct
* `{ "a": 1 }` - still correct, but an array was expected by the recipient

**Example 2**: strings that look like integers are serialized as integers
* `{ "a": "00012345" }` - correct
* `{ "a": "XY067891" }` - correct
* `{ "a": 10012345 }` - still correct, but a string was expected

Both of these cases can be resolved at the deser end, but it's a hassle and requires some good knowledge of Serde. There is also an unmerged (abandoned?) PR that can address this problem (https://github.com/serde-rs/serde/pull/1623). It's not a big problem if I'm both, the producer and the consumer.

On the other hand, a JSON document for a wider audience should really be consistent.

## Proposed solution

1. Add a config param with a list of JSON property names and their data types
2. Enforce the data type if there is a property name match

## Questions

1. There will be a performance hit
2. What to do with the errors? It can also be set via config (ignore, panic)
3. Are there any other possible inconsistencies other than the 2 examples above? Boolean values as boolean vs string?
4. Is it even the right solution to the problem? We could just give examples of custom deser code to deal with Ex1 and Ex2.

Using just the property name (e.g. `flat_number`) to identify the node may be too ambiguous. Using the whole path (e.g. `user.address.flat_number`) can get too verbose (e.g. `user.address. ...`, `shipping.address. ...`) and will required full awareness of the node about its position in the tree. The compromise can be a pattern (e.g. `*.flat_number`), but that gets really complicated really quick.

@AlecTroemel , any thoughts? Feel free to ignore if it's not something you have time for.

**Comment by AlecTroemel** [comment]
@rimutaka Is the problem that its impossible to tell whether `<a><b>value</b><a>` is 
1. a array of length 1 `{a: [{b: "value"}]}` 
2. a parent-child relationship `{a: {b: "value}}`

Thinking about that situation now, I think it makes more sense to go with option 1 (treat everything as a list).  

 It would maybe help me if you could provide the input XML for your examples.

**Comment by rimutaka** [comment]
A reference to the same problem on Reddit: https://www.reddit.com/r/rust/comments/jh60t8/fast_xml_to_json_converter_crate_revived_and/

**Comment by rimutaka** [comment]
@AlecTroemel Alec, I am prototyping a solution for this and ran into something I do not understand.

`fn parse_text()` has this `if` in https://github.com/AlecTroemel/quickxml_to_serde/blob/master/src/lib.rs#L126

Here is the full snippet:
```rust
    if let Ok(v) = text.parse::<u64>() {
        // don't parse octal numbers and those with leading 0
        if text.starts_with("0") && v != 0 && leading_zero_as_string {
            return Value::String(text.into());
        }
        return Value::Number(Number::from(v));
    }
```

**Why do we need `v != 0` as a condition there?**

If we had these test cases they would fail because the values are legit zero and `v != 0` prevents them from being strings:
```rust
assert_eq!("0", parse_text("0", true));
assert_eq!("0000", parse_text("0000", true));
```

Can I remove `v != 0` or is there some reason why it's there?

**Comment by AlecTroemel** [comment]
@rimutaka I did some digging, looks like that `v != 0` was introduced in this commit https://github.com/AlecTroemel/quickxml_to_serde/commit/db78ecc070d0a5648714d00738df7e13c7a5c7a5. I'm still working out why it's there :thinking:

**Comment by rimutaka** [comment]
I removed the breaking change and added an example file. I guess v 0.4.2 is more appropriate now - we added an optional feature.

Re `v!=0` check ... 

If the check is present it would produce an inconsistent result in an example like this `{ "a": ["03", "02", "01", 0] }`

**Comment by AlecTroemel** [comment]
@rimutaka not sure I understand the inconsistent result example. What would the input XML look like to produce that JSON? To be clear, your talking the suggestion [in this comment](https://github.com/AlecTroemel/quickxml_to_serde/pull/10#issuecomment-717477234) causing the inconsistency correct?

**Comment by rimutaka** [comment]
@AlecTroemel , Alec, yes, sorry, I accidentally cross-posted here from the PR. 

I think I see the flaw in my thinking.

If we have a set of numbers padded with zeros on the left, e.g. RGB values, the "zero" will also be padded. 
E.g. red `000255000`, black `000000000` and both will be converted to strings like in `assert_eq!("0000", parse_text("0000", true, &JsonType::Infer));`

If we have a set of values that are not padded and then there is zero, it should be converted into a number like in `assert_eq!(0, parse_text("0", true, &JsonType::Infer));`

So I should just put that `v!=0` check back.

**Comment by rimutaka** [comment]
I think the balance of the universe has been restored. Here is the check 
```rust
    if let Ok(v) = text.parse::<u64>() {
        // don't parse octal numbers and those with leading 0
        // `text` value "0" will always be converted into number 0, "0000" may be converted
        // into 0 or "0000" depending on `leading_zero_as_string`
        if leading_zero_as_string && text.starts_with("0") && (v != 0 || text.len() > 1) {
            return Value::String(text.into());
        }
        return Value::Number(Number::from(v));
    }
```
that satisfies these test cases
```rust
        assert_eq!(0.0, parse_text("0.0", false, &JsonType::Infer));
        assert_eq!(0, parse_text("0", false, &JsonType::Infer));
        assert_eq!(0, parse_text("0000", false, &JsonType::Infer));
        assert_eq!(0, parse_text("0", true, &JsonType::Infer));
        assert_eq!("0000", parse_text("0000", true, &JsonType::Infer));
```

I also re-arranged the order of the predicates to make the check less costly.

Sorry for creating the confusion, but I'm glad we got to the bottom of it :)

**Comment by rimutaka** [comment]
PR #10 merged. The code ran well in our prod. I'd like to add a few more fixes before making a release.
